import { readdirSync } from "node:fs";
import { basename, resolve } from "node:path";
import mri from "mri";
import {
  createBatiConfig,
  createE2EWorkspace,
  updatePackageJson,
  updateTsconfig,
  updateVitestConfig,
} from "./common.js";

async function prepare(flags: string[], testFiles: string) {
  const projectDir = ".";
  const packedTestUtils = readdirSync(projectDir).find((f) => f.startsWith("batijs-tests-utils-"));

  if (!packedTestUtils) {
    throw new Error("No packed test utils found.");
  }

  // @ts-expect-error
  const packageManagerSpec = `bun@${Bun.version}`;

  if (flags.includes("dokploy")) {
    // The workflow invokes us with cwd already set to the sibling `<app>.e2e` dir
    // (the tgz + spec files were linked into it earlier). The app dir stays clean —
    // we only populate the host workspace.
    const e2eDirName = basename(resolve(projectDir));
    const appName = e2eDirName.endsWith(".e2e") ? e2eDirName.slice(0, -".e2e".length) : e2eDirName;
    await createE2EWorkspace(projectDir, appName, flags, `./${packedTestUtils}`, testFiles, packageManagerSpec);
    return;
  }

  await updatePackageJson(projectDir, flags, `./${packedTestUtils}`, packageManagerSpec);
  await updateTsconfig(projectDir);
  await updateVitestConfig(projectDir, testFiles);
  // knip.json is generated by CLI with --knip flag
  await createBatiConfig(projectDir, flags);
}

const argv = process.argv.slice(2);
const args = mri<Record<string, unknown>>(argv);
const flags: string[] = [];

for (const [k, v] of Object.entries(args)) {
  if (v === true) {
    flags.push(k);
  }
}

await prepare(flags, args["test-files"] as string);
