import { readdirSync } from "node:fs";
import { basename, resolve } from "node:path";
import mri from "mri";
import { createE2EWorkspace } from "./common.js";

async function prepare(flags: string[], testFiles: string) {
  // The workflow invokes us with cwd already set to the sibling `<app>.e2e/`
  // (the tgz + spec files were copied/symlinked into it earlier). The sibling
  // app is one level up and shares the same base name minus the `.e2e` suffix.
  const projectDir = ".";
  const packedTestUtils = readdirSync(projectDir).find((f) => f.startsWith("batijs-tests-utils-"));

  if (!packedTestUtils) {
    throw new Error("No packed test utils found.");
  }

  // @ts-expect-error
  const packageManagerSpec = `bun@${Bun.version}`;

  const e2eDirName = basename(resolve(projectDir));
  const appName = e2eDirName.endsWith(".e2e") ? e2eDirName.slice(0, -".e2e".length) : e2eDirName;
  // knip.json is generated by the CLI when --knip is passed.
  await createE2EWorkspace({
    e2eDir: projectDir,
    appName,
    flags,
    testsUtilsRef: `./${packedTestUtils}`,
    testFiles,
    packageManagerSpec,
  });
}

const argv = process.argv.slice(2);
const args = mri<Record<string, unknown>>(argv);
const flags: string[] = [];

for (const [k, v] of Object.entries(args)) {
  if (v === true) {
    flags.push(k);
  }
}

await prepare(flags, args["test-files"] as string);
