import { readdirSync } from "node:fs";
import mri from "mri";
import {
  createBatiConfig,
  createTurboConfig,
  updatePackageJson,
  updateTsconfig,
  updateVitestConfig,
} from "./common.js";

async function prepare(flags: string[], testFiles: string) {
  const projectDir = ".";
  const packedTestUtils = readdirSync(projectDir).find((f) => f.startsWith("batijs-tests-utils-"));

  if (!packedTestUtils) {
    throw new Error("No packed test utils found.");
  }

  // @ts-expect-error
  await updatePackageJson(projectDir, flags, `./${packedTestUtils}`, `bun@${Bun.version}`, true);
  await updateTsconfig(projectDir);
  await updateVitestConfig(projectDir, testFiles);
  await createTurboConfig({
    tmpdir: projectDir,
  });
  // knip.json is generated by CLI with --knip flag
  await createBatiConfig(projectDir, flags);
}

const argv = process.argv.slice(2);
const args = mri<Record<string, unknown>>(argv);
const flags: string[] = [];

for (const [k, v] of Object.entries(args)) {
  if (v === true) {
    flags.push(k);
  }
}

await prepare(flags, args["test-files"] as string);
