packages:
  - packages/*
  - boilerplates/*
  - website

autoInstallPeers: false

hoistPattern:
  - '@batijs/*'
  - '!@batijs/compile'
  - '!@batijs/core'
  - '!@batijs/build'
  - '!@batijs/features'

injectWorkspacePackages: true

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@browserless/goto'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - aws-sdk
  - better-sqlite3
  - es5-ext
  - esbuild
  - oxc-resolver
  - prisma
  - protobufjs
  - puppeteer
  - re2
  - sharp
  - workerd

packageManagerStrictVersion: false

shamefullyHoist: true
