%%{
  init: {
    "theme": "dark"
  }
}%%

flowchart TB
    Base_doc_frontend -- more/complete frontend docs --> Vike_doc
    Base_boilerplate -. generates CLI command .-> Bati_gen
    Bati -- uses --> Concepts

    subgraph Base["Base (full-stack &quot;framework&quot;)"]
        Base_boilerplate("
            Boilerplate Assembler UI
        ")
        Base_doc_fullstack("
            Backend docs
        ")
        Base_doc_frontend("
            Frontend docs
            <small style='opacity: 0.5'>Only basics and high-level</small>
        ")
        Base_Solide("
            <s>Solide</s>
            <small style='opacity: 0.5'>Becomes Base</small>
        ")
        Base_Restack("
            <s>Restack</s>
            <small style='opacity: 0.5'>Becomes Base</small>
        ")
    end

    subgraph Vike["Vike (frontend framework)"]
        Vike_doc("Docs")
        Vike_integrations("
           vike-*
           <small style='opacity: 0.5'>Integration for React/Vue/Solid/...</small>
        ")
        Vike_create("
          create-vike
          <small style='opacity: 0.5'>Minimal vanilla &quot;dumb&quot; boilerplate</small>
        ")
        Vike_boilerplates("
          <s>Boilerplates</s>
          <small style='opacity: 0.5'>=> Base &quot;smart&quot; boilerplate</small>
        ")
    end

    subgraph Bati["Bâti"]
        Bati_gen("
          Generator
          <small style='opacity: 0.5'>CLI command => boilerplate</small>
        ")
        Bati_frontend("
          Frontend Files
          <small style='opacity: 0.5'>w/ different variants \n for React/Solid/Vue</small>
        ")
        Bati_backend("
          Backend Files
          <small style='opacity: 0.5'>w/ different variants \n for EdgeDB/Prisma/...</small>
        ")
    end

    subgraph Concepts
        direction TB
        Concepts_auth("Auth")
        Concepts_db("DB")
        Concepts_web("Web server")
        Concepts_etc("etc...")
    end
