%%{
  init: {
    "theme": "dark"
  }
}%%

flowchart TB
    Base_Solide -- low level doc --> Vike_doc
    Base_Restack -- low level doc --> Vike_doc
    Base_generic -- low level doc --> Vike_doc
    Base_bati_CLI -. CLI .-> Bati
    Bati -.-> Boilerplates
    Bati -.-> Integrations
    Vike_boilerplates == becomes ==> Boilerplates
    Vike_create -- uses --> Concepts
    Boilerplates -- uses --> Concepts
    Integrations --> Final
    Boilerplates --> Final

    Bati["Bâti"]

    Final(("User app"))

    subgraph Base
        Base_bati_CLI("
            Bati CLI generator
        ")
        Base_Solide("
            Solide
            <small style='opacity: 0.5'>High level doc</small>
        ")
        Base_Restack("
            Restack
            <small style='opacity: 0.5'>High level doc</small>
        ")
        Base_generic("
            Or generic doc?
            <small style='opacity: 0.5'>High level doc</small>
        ")
    end

    subgraph Vike
        Vike_lib("Vike")
        Vike_boilerplates("Boilerplates")
        Vike_doc("Documentation")
        Vike_create("create-vps")
        Vike_examples("Examples")
    end

    subgraph Integrations
        Starters_solid("vike-solid")
        Starters_react("vike-react")
        Starters_vue("vike-vue")
    end

    subgraph Boilerplates["Bati boilerplates"]
        Boilerplates_solid("Solid starter")
        Boilerplates_react("React starter")
        Boilerplates_vue("Vue starter")
    end

    subgraph Concepts
        direction TB
        Concepts_auth("Auth")
        Concepts_db("DB")
        Concepts_web("Web server")
        Concepts_etc("etc...")
    end

