import { appendToEnv, randomBytes, type TransformerProps } from "@batijs/core";

export default async function getEnv(props: TransformerProps) {
  const envContent = await props.readfile?.();

  return appendToEnv(envContent, "SECRET", randomBytes(32).toString("hex"), "Randomly generated by Bati CLI");
}
