import { defineConfig } from "@batijs/core/config";

export default defineConfig({
  if(meta) {
    return meta.BATI.has("drizzle");
  },
  // Migrations (generated by drizzle:generate), the drizzle-kit config, and the shared env
  // loader that drizzle.config.ts imports all run as raw source in the production runner.
  deploy: ["database/migrations", "drizzle.config.ts", "server/load.ts"],
  nextSteps(_meta, packageManager, { bold }) {
    return [
      {
        type: "text",
        step: `Add your drizzle ${bold("DATABASE_URL")} to the .env file. Check ${bold("TODO.md")} for details`,
      },
      {
        type: "command",
        step: `${packageManager} drizzle:generate`,
      },
      {
        type: "command",
        step: `${packageManager} drizzle:migrate`,
      },
    ];
  },
});
