# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy pages

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install
    - name: Build packages
      run: pnpm run build
    - run: pnpm run build:pages
      working-directory: website
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        force: false
        folder: website/dist/client
        clean-exclude: pr-preview/
        token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        repository-name: batijs/batijs.github.io
        clean: true
