name: Publish packages to npmjs on PR merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths-ignore:
      - 'website/**'

# Conflicts with publish-widget.yml
concurrency:
  group: publish
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write  # Required for OIDC

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Fetch latest
        run: |
          git fetch --tags origin
          git pull origin ${{ github.ref_name }}

      - uses: oven-sh/setup-bun@v2
        name: Install bun
        with:
          bun-version: 1.3.11

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          # Note: Trusted publishing requires npm CLI version 11.5.1 or later and Node version 22.14.0 or higher.
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: bun install

      - name: Configure git before publish
        run: |
          git config --global user.name "Joël Charles"
          git config --global user.email "joel.charles91@gmail.com"

      - run: bun run release:ci
