on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

concurrency:
  group: tests-entry-os-${{ inputs.os }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22
  BUN_VERSION: "1.3.11"

jobs:
  suite:
    runs-on: ${{ inputs.os }}

    name: ${{ inputs.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        name: Install bun
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: bun install

      - name: Build packages
        run: bun run build

      - name: Run tests
        run: bun run test

      - name: Deploy CLI locally
        run: bun run scripts/deploy.ts ./packages/cli ./bati-cli

      - name: Archive Bati CLI
        uses: actions/upload-artifact@v7
        with:
          name: bati-cli-${{ inputs.os }}-${{ env.NODE_VERSION }}
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          include-hidden-files: true
          path: ./bati-cli/*

      - name: Deploy tests locally
        run: bun run scripts/deploy.ts ./packages/tests ./bati-tests

      - name: Archive Bati tests
        uses: actions/upload-artifact@v7
        with:
          name: bati-tests-${{ inputs.os }}-${{ env.NODE_VERSION }}
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          include-hidden-files: true
          path: ./bati-tests/dist/*

      - name: Pack tests-utils
        run: bun pm pack
        working-directory: ./packages/tests-utils

      - name: Archive tests-utils
        uses: actions/upload-artifact@v7
        with:
          name: tests-utils-${{ inputs.os }}-${{ env.NODE_VERSION }}
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          include-hidden-files: true
          path: ./packages/tests-utils/batijs-tests-utils-*.tgz

      - name: Archive tests files
        uses: actions/upload-artifact@v7
        with:
          name: tests-files-${{ inputs.os }}-${{ env.NODE_VERSION }}
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          include-hidden-files: true
          path: ./packages/tests/tests/*
