name: Tests

on:
  pull_request:
    paths-ignore:
      - "website/**"
  push:
    # Ensures cache is computed on main branch so that it can be reused on all PRs
    branches: [ "main" ]
    paths-ignore:
      - "website/**"

concurrency:
  group: tests-entry-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22
  BUN_VERSION: "1.3.11"

# Provides better concurrency compared to only using matrix
jobs:
  # Fast Windows tests
  init-windows:
    name: Windows

    uses: ./.github/workflows/reusable.init-tests.yml
    secrets: inherit
    with:
      os: windows-latest

  tests-windows:
    needs: init-windows

    name: Run ${{ matrix.flags }} (windows)

    uses: ./.github/workflows/reusable.run-tests.yml
    secrets: inherit
    with:
      os: windows-latest
      destination: react--hono--authjs--eslint--biome
      flags: --react --hono --authjs --eslint --biome
      test-files: FRAMEWORK+SERVER+AUTH.spec.ts

  # Fast MacOS tests
  init-macos:
    name: MacOS

    uses: ./.github/workflows/reusable.init-tests.yml
    secrets: inherit
    with:
      os: macos-latest

  tests-macos:
    needs: init-macos

    name: Run ${{ matrix.flags }} (mac)

    uses: ./.github/workflows/reusable.run-tests.yml
    secrets: inherit
    with:
      os: macos-latest
      destination: react--hono--authjs--eslint--biome
      flags: --react --hono --authjs --eslint --biome
      test-files: FRAMEWORK+SERVER+AUTH.spec.ts

  # Full Ubuntu tests
  init-ubuntu:
    name: Ubuntu

    uses: ./.github/workflows/reusable.init-tests.yml
    secrets: inherit
    with:
      os: ubuntu-latest

  tests-ubuntu:
    needs: init-ubuntu
    strategy:
      matrix:
        # bun run test:e2e:workflow-write
        destination:
          - react--plausible.io--eslint--biome--oxlint
          - react--google-analytics--eslint--biome--oxlint
          - react--eslint--biome--oxlint
          - vue--plausible.io--eslint--biome--oxlint
          - vue--google-analytics--eslint--biome--oxlint
          - vue--eslint--biome--oxlint
          - solid--plausible.io--eslint--biome--oxlint
          - solid--google-analytics--eslint--biome--oxlint
          - solid--eslint--biome--oxlint
          - react--tailwindcss--eslint--biome--oxlint
          - vue--tailwindcss--daisyui--eslint--biome--oxlint
          - react--hono--authjs--eslint--biome--oxlint
          - react--hono--auth0--eslint--biome--oxlint
          - react--express--authjs--eslint--biome--oxlint
          - react--express--auth0--eslint--biome--oxlint
          - react--fastify--authjs--eslint--biome--oxlint
          - react--fastify--auth0--eslint--biome--oxlint
          - react--elysia--authjs--eslint--biome--oxlint
          - react--elysia--auth0--eslint--biome--oxlint
          - vue--hono--authjs--eslint--biome--oxlint
          - vue--hono--auth0--eslint--biome--oxlint
          - vue--express--authjs--eslint--biome--oxlint
          - vue--express--auth0--eslint--biome--oxlint
          - vue--fastify--authjs--eslint--biome--oxlint
          - vue--fastify--auth0--eslint--biome--oxlint
          - vue--elysia--authjs--eslint--biome--oxlint
          - vue--elysia--auth0--eslint--biome--oxlint
          - solid--hono--authjs--eslint--biome--oxlint
          - solid--hono--auth0--eslint--biome--oxlint
          - solid--express--authjs--eslint--biome--oxlint
          - solid--express--auth0--eslint--biome--oxlint
          - solid--fastify--authjs--eslint--biome--oxlint
          - solid--fastify--auth0--eslint--biome--oxlint
          - solid--elysia--authjs--eslint--biome--oxlint
          - solid--elysia--auth0--eslint--biome--oxlint
          - react--hono--cloudflare--auth0--eslint--biome--oxlint
          - react--hono--dokploy--authjs--eslint--biome--oxlint
          - react--hono--dokploy--auth0--eslint--biome--oxlint
          - react--hono--better-auth--sqlite--drizzle--eslint--biome--oxlint
          - react--express--better-auth--sqlite--prisma--eslint--biome--oxlint
          - react--fastify--better-auth--sqlite--kysely--eslint--biome--oxlint
          - react--elysia--better-auth--sqlite--eslint--biome--oxlint
          - vue--hono--better-auth--sqlite--drizzle--eslint--biome--oxlint
          - vue--express--better-auth--sqlite--prisma--eslint--biome--oxlint
          - vue--fastify--better-auth--sqlite--kysely--eslint--biome--oxlint
          - vue--elysia--better-auth--sqlite--eslint--biome--oxlint
          - solid--hono--better-auth--sqlite--drizzle--eslint--biome--oxlint
          - solid--express--better-auth--sqlite--prisma--eslint--biome--oxlint
          - solid--fastify--better-auth--sqlite--kysely--eslint--biome--oxlint
          - solid--elysia--better-auth--sqlite--eslint--biome--oxlint
          - solid--hono--better-auth--postgres--drizzle--eslint--biome--oxlint
          - solid--express--better-auth--postgres--kysely--eslint--biome--oxlint
          - solid--fastify--better-auth--postgres--eslint--biome--oxlint
          - react--hono--cloudflare--better-auth--sqlite--drizzle--eslint--biome--oxlint
          - react--hono--cloudflare--better-auth--sqlite--eslint--biome--oxlint
          - solid--express--trpc--sqlite--drizzle--eslint--biome--oxlint
          - solid--express--trpc--sqlite--kysely--eslint--biome--oxlint
          - solid--express--trpc--sqlite--eslint--biome--oxlint
          - solid--express--telefunc--sqlite--drizzle--eslint--biome--oxlint
          - solid--express--telefunc--sqlite--kysely--eslint--biome--oxlint
          - solid--express--telefunc--sqlite--eslint--biome--oxlint
          - solid--express--ts-rest--sqlite--drizzle--eslint--biome--oxlint
          - solid--express--ts-rest--sqlite--kysely--eslint--biome--oxlint
          - solid--express--ts-rest--sqlite--eslint--biome--oxlint
          - solid--express--sqlite--drizzle--eslint--biome--oxlint
          - solid--express--sqlite--kysely--eslint--biome--oxlint
          - solid--express--sqlite--eslint--biome--oxlint
          - solid--elysia--trpc--sqlite--drizzle--eslint--biome--oxlint
          - solid--elysia--trpc--sqlite--kysely--eslint--biome--oxlint
          - solid--elysia--trpc--sqlite--eslint--biome--oxlint
          - solid--elysia--telefunc--sqlite--drizzle--eslint--biome--oxlint
          - solid--elysia--telefunc--sqlite--kysely--eslint--biome--oxlint
          - solid--elysia--telefunc--sqlite--eslint--biome--oxlint
          - solid--elysia--ts-rest--sqlite--drizzle--eslint--biome--oxlint
          - solid--elysia--ts-rest--sqlite--kysely--eslint--biome--oxlint
          - solid--elysia--ts-rest--sqlite--eslint--biome--oxlint
          - solid--elysia--sqlite--drizzle--eslint--biome--oxlint
          - solid--elysia--sqlite--kysely--eslint--biome--oxlint
          - solid--elysia--sqlite--eslint--biome--oxlint
          - solid--hono--trpc--sqlite--drizzle--eslint--biome--oxlint
          - solid--hono--trpc--sqlite--kysely--eslint--biome--oxlint
          - solid--hono--trpc--sqlite--eslint--biome--oxlint
          - solid--hono--telefunc--sqlite--drizzle--eslint--biome--oxlint
          - solid--hono--telefunc--sqlite--kysely--eslint--biome--oxlint
          - solid--hono--telefunc--sqlite--eslint--biome--oxlint
          - solid--hono--ts-rest--sqlite--drizzle--eslint--biome--oxlint
          - solid--hono--ts-rest--sqlite--kysely--eslint--biome--oxlint
          - solid--hono--ts-rest--sqlite--eslint--biome--oxlint
          - solid--hono--sqlite--drizzle--eslint--biome--oxlint
          - solid--hono--sqlite--kysely--eslint--biome--oxlint
          - solid--hono--sqlite--eslint--biome--oxlint
          - solid--fastify--trpc--sqlite--drizzle--eslint--biome--oxlint
          - solid--fastify--trpc--sqlite--kysely--eslint--biome--oxlint
          - solid--fastify--trpc--sqlite--eslint--biome--oxlint
          - solid--fastify--telefunc--sqlite--drizzle--eslint--biome--oxlint
          - solid--fastify--telefunc--sqlite--kysely--eslint--biome--oxlint
          - solid--fastify--telefunc--sqlite--eslint--biome--oxlint
          - solid--fastify--ts-rest--sqlite--drizzle--eslint--biome--oxlint
          - solid--fastify--ts-rest--sqlite--kysely--eslint--biome--oxlint
          - solid--fastify--ts-rest--sqlite--eslint--biome--oxlint
          - solid--fastify--sqlite--drizzle--eslint--biome--oxlint
          - solid--fastify--sqlite--kysely--eslint--biome--oxlint
          - solid--fastify--sqlite--eslint--biome--oxlint
          - solid--express--trpc--eslint--biome--oxlint
          - solid--express--telefunc--eslint--biome--oxlint
          - solid--express--ts-rest--eslint--biome--oxlint
          - solid--express--eslint--biome--oxlint
          - solid--hono--trpc--eslint--biome--oxlint
          - solid--hono--telefunc--eslint--biome--oxlint
          - solid--hono--ts-rest--eslint--biome--oxlint
          - solid--hono--eslint--biome--oxlint
          - solid--fastify--trpc--eslint--biome--oxlint
          - solid--fastify--telefunc--eslint--biome--oxlint
          - solid--fastify--ts-rest--eslint--biome--oxlint
          - solid--fastify--eslint--biome--oxlint
          - solid--elysia--trpc--eslint--biome--oxlint
          - solid--elysia--telefunc--eslint--biome--oxlint
          - solid--elysia--ts-rest--eslint--biome--oxlint
          - solid--elysia--eslint--biome--oxlint
          - react--hono--trpc--eslint--biome--oxlint
          - react--hono--telefunc--eslint--biome--oxlint
          - react--hono--ts-rest--eslint--biome--oxlint
          - react--hono--eslint--biome--oxlint
          - vue--hono--trpc--eslint--biome--oxlint
          - vue--hono--telefunc--eslint--biome--oxlint
          - vue--hono--ts-rest--eslint--biome--oxlint
          - vue--hono--eslint--biome--oxlint
          - solid--express--telefunc--postgres--drizzle--eslint--biome--oxlint
          - solid--express--telefunc--postgres--kysely--eslint--biome--oxlint
          - solid--express--telefunc--postgres--eslint--biome--oxlint
          - solid--express--postgres--drizzle--eslint--biome--oxlint
          - solid--express--postgres--kysely--eslint--biome--oxlint
          - solid--express--postgres--eslint--biome--oxlint
          - solid--hono--telefunc--postgres--drizzle--eslint--biome--oxlint
          - solid--hono--telefunc--postgres--kysely--eslint--biome--oxlint
          - solid--hono--telefunc--postgres--eslint--biome--oxlint
          - solid--hono--postgres--drizzle--eslint--biome--oxlint
          - solid--hono--postgres--kysely--eslint--biome--oxlint
          - solid--hono--postgres--eslint--biome--oxlint
          - solid--hono--cloudflare--trpc--sqlite--drizzle--eslint--biome--oxlint
          - solid--hono--cloudflare--trpc--sqlite--kysely--eslint--biome--oxlint
          - solid--hono--cloudflare--trpc--sqlite--eslint--biome--oxlint
          - solid--hono--cloudflare--telefunc--sqlite--drizzle--eslint--biome--oxlint
          - solid--hono--cloudflare--telefunc--sqlite--kysely--eslint--biome--oxlint
          - solid--hono--cloudflare--telefunc--sqlite--eslint--biome--oxlint
          - solid--hono--cloudflare--ts-rest--sqlite--drizzle--eslint--biome--oxlint
          - solid--hono--cloudflare--ts-rest--sqlite--kysely--eslint--biome--oxlint
          - solid--hono--cloudflare--ts-rest--sqlite--eslint--biome--oxlint
          - solid--hono--cloudflare--sqlite--drizzle--eslint--biome--oxlint
          - solid--hono--cloudflare--sqlite--kysely--eslint--biome--oxlint
          - solid--hono--cloudflare--sqlite--eslint--biome--oxlint
          - react--hono--dokploy--telefunc--sqlite--drizzle--eslint--biome--oxlint
          - react--hono--dokploy--telefunc--sqlite--eslint--biome--oxlint
          - react--hono--dokploy--telefunc--postgres--drizzle--eslint--biome--oxlint
          - react--hono--dokploy--telefunc--postgres--eslint--biome--oxlint
          - react--elysia--dokploy--telefunc--sqlite--drizzle--eslint--biome--oxlint
          - react--elysia--dokploy--telefunc--postgres--drizzle--eslint--biome--oxlint
          - aws--react--hono--eslint--biome--oxlint
          - react--cloudflare--hono--eslint--biome--oxlint
          - react--cloudflare--eslint--biome--oxlint
          - react--edgeone--eslint--biome--oxlint
          - vue--netlify--eslint--biome--oxlint
          - solid--prettier--eslint--biome--oxlint
          - react--hono--prisma--sqlite--eslint--biome--oxlint
          - vue--hono--prisma--postgres--eslint--biome--oxlint
          - react--sentry--eslint--biome--oxlint
          - vue--sentry--eslint--biome--oxlint
          - solid--sentry--eslint--biome--oxlint
          - react--claude
          - vue--claude
          - solid--claude
          - react--hono--trpc--sqlite--drizzle--codex--gemini
          - solid--storybook--eslint
          - react--vercel--hono--eslint--biome--oxlint
          - react--vercel--express--eslint--biome--oxlint
          - react--vercel--fastify--eslint--biome--oxlint
          - react--vercel--elysia--eslint--biome--oxlint
          - react--vercel--eslint--biome--oxlint
          - react--compiled-css--eslint--biome
          - react--mantine--eslint--biome
          - react--ts-rest--hono--eslint
          - react--ts-rest--hono--biome
          - react--ts-rest--hono--oxlint
        # bun run test:e2e:workflow-write
        include:
          - destination: react--plausible.io--eslint--biome--oxlint
            flags: --react --plausible.io --eslint --biome --oxlint
            test-files: FRAMEWORK+ANALYTICS.spec.ts
          - destination: react--google-analytics--eslint--biome--oxlint
            flags: --react --google-analytics --eslint --biome --oxlint
            test-files: FRAMEWORK+ANALYTICS.spec.ts
          - destination: react--eslint--biome--oxlint
            flags: --react --eslint --biome --oxlint
            test-files: FRAMEWORK+ANALYTICS.spec.ts
          - destination: vue--plausible.io--eslint--biome--oxlint
            flags: --vue --plausible.io --eslint --biome --oxlint
            test-files: FRAMEWORK+ANALYTICS.spec.ts
          - destination: vue--google-analytics--eslint--biome--oxlint
            flags: --vue --google-analytics --eslint --biome --oxlint
            test-files: FRAMEWORK+ANALYTICS.spec.ts
          - destination: vue--eslint--biome--oxlint
            flags: --vue --eslint --biome --oxlint
            test-files: FRAMEWORK+ANALYTICS.spec.ts
          - destination: solid--plausible.io--eslint--biome--oxlint
            flags: --solid --plausible.io --eslint --biome --oxlint
            test-files: FRAMEWORK+ANALYTICS.spec.ts
          - destination: solid--google-analytics--eslint--biome--oxlint
            flags: --solid --google-analytics --eslint --biome --oxlint
            test-files: FRAMEWORK+ANALYTICS.spec.ts
          - destination: solid--eslint--biome--oxlint
            flags: --solid --eslint --biome --oxlint
            test-files: FRAMEWORK+ANALYTICS.spec.ts
          - destination: react--tailwindcss--eslint--biome--oxlint
            flags: --react --tailwindcss --eslint --biome --oxlint
            test-files: FRAMEWORK+CSS.spec.ts
          - destination: vue--tailwindcss--daisyui--eslint--biome--oxlint
            flags: --vue --tailwindcss --daisyui --eslint --biome --oxlint
            test-files: FRAMEWORK+CSS.spec.ts
          - destination: react--hono--authjs--eslint--biome--oxlint
            flags: --react --hono --authjs --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--hono--auth0--eslint--biome--oxlint
            flags: --react --hono --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--express--authjs--eslint--biome--oxlint
            flags: --react --express --authjs --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--express--auth0--eslint--biome--oxlint
            flags: --react --express --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--fastify--authjs--eslint--biome--oxlint
            flags: --react --fastify --authjs --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--fastify--auth0--eslint--biome--oxlint
            flags: --react --fastify --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--elysia--authjs--eslint--biome--oxlint
            flags: --react --elysia --authjs --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--elysia--auth0--eslint--biome--oxlint
            flags: --react --elysia --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: vue--hono--authjs--eslint--biome--oxlint
            flags: --vue --hono --authjs --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: vue--hono--auth0--eslint--biome--oxlint
            flags: --vue --hono --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: vue--express--authjs--eslint--biome--oxlint
            flags: --vue --express --authjs --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: vue--express--auth0--eslint--biome--oxlint
            flags: --vue --express --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: vue--fastify--authjs--eslint--biome--oxlint
            flags: --vue --fastify --authjs --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: vue--fastify--auth0--eslint--biome--oxlint
            flags: --vue --fastify --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: vue--elysia--authjs--eslint--biome--oxlint
            flags: --vue --elysia --authjs --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: vue--elysia--auth0--eslint--biome--oxlint
            flags: --vue --elysia --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--hono--authjs--eslint--biome--oxlint
            flags: --solid --hono --authjs --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--hono--auth0--eslint--biome--oxlint
            flags: --solid --hono --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--express--authjs--eslint--biome--oxlint
            flags: --solid --express --authjs --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--express--auth0--eslint--biome--oxlint
            flags: --solid --express --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--fastify--authjs--eslint--biome--oxlint
            flags: --solid --fastify --authjs --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--fastify--auth0--eslint--biome--oxlint
            flags: --solid --fastify --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--elysia--authjs--eslint--biome--oxlint
            flags: --solid --elysia --authjs --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--elysia--auth0--eslint--biome--oxlint
            flags: --solid --elysia --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--hono--cloudflare--auth0--eslint--biome--oxlint
            flags: --react --hono --cloudflare --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--hono--dokploy--authjs--eslint--biome--oxlint
            flags: --react --hono --dokploy --authjs --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--hono--dokploy--auth0--eslint--biome--oxlint
            flags: --react --hono --dokploy --auth0 --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--hono--better-auth--sqlite--drizzle--eslint--biome--oxlint
            flags: --react --hono --better-auth --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--express--better-auth--sqlite--prisma--eslint--biome--oxlint
            flags: --react --express --better-auth --sqlite --prisma --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--fastify--better-auth--sqlite--kysely--eslint--biome--oxlint
            flags: --react --fastify --better-auth --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--elysia--better-auth--sqlite--eslint--biome--oxlint
            flags: --react --elysia --better-auth --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: vue--hono--better-auth--sqlite--drizzle--eslint--biome--oxlint
            flags: --vue --hono --better-auth --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: vue--express--better-auth--sqlite--prisma--eslint--biome--oxlint
            flags: --vue --express --better-auth --sqlite --prisma --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: vue--fastify--better-auth--sqlite--kysely--eslint--biome--oxlint
            flags: --vue --fastify --better-auth --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: vue--elysia--better-auth--sqlite--eslint--biome--oxlint
            flags: --vue --elysia --better-auth --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--hono--better-auth--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --hono --better-auth --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--express--better-auth--sqlite--prisma--eslint--biome--oxlint
            flags: --solid --express --better-auth --sqlite --prisma --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--fastify--better-auth--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --fastify --better-auth --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--elysia--better-auth--sqlite--eslint--biome--oxlint
            flags: --solid --elysia --better-auth --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--hono--better-auth--postgres--drizzle--eslint--biome--oxlint
            flags: --solid --hono --better-auth --postgres --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--express--better-auth--postgres--kysely--eslint--biome--oxlint
            flags: --solid --express --better-auth --postgres --kysely --eslint
              --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--fastify--better-auth--postgres--eslint--biome--oxlint
            flags: --solid --fastify --better-auth --postgres --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--hono--cloudflare--better-auth--sqlite--drizzle--eslint--biome--oxlint
            flags: --react --hono --cloudflare --better-auth --sqlite --drizzle
              --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: react--hono--cloudflare--better-auth--sqlite--eslint--biome--oxlint
            flags: --react --hono --cloudflare --better-auth --sqlite --eslint
              --biome --oxlint
            test-files: FRAMEWORK+SERVER+AUTH.spec.ts
          - destination: solid--express--trpc--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --express --trpc --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--trpc--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --express --trpc --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--trpc--sqlite--eslint--biome--oxlint
            flags: --solid --express --trpc --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--telefunc--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --express --telefunc --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--telefunc--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --express --telefunc --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--telefunc--sqlite--eslint--biome--oxlint
            flags: --solid --express --telefunc --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--ts-rest--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --express --ts-rest --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--ts-rest--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --express --ts-rest --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--ts-rest--sqlite--eslint--biome--oxlint
            flags: --solid --express --ts-rest --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --express --sqlite --drizzle --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --express --sqlite --kysely --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--sqlite--eslint--biome--oxlint
            flags: --solid --express --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--trpc--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --elysia --trpc --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--trpc--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --elysia --trpc --sqlite --kysely --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--trpc--sqlite--eslint--biome--oxlint
            flags: --solid --elysia --trpc --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--telefunc--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --elysia --telefunc --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--telefunc--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --elysia --telefunc --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--telefunc--sqlite--eslint--biome--oxlint
            flags: --solid --elysia --telefunc --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--ts-rest--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --elysia --ts-rest --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--ts-rest--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --elysia --ts-rest --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--ts-rest--sqlite--eslint--biome--oxlint
            flags: --solid --elysia --ts-rest --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --elysia --sqlite --drizzle --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --elysia --sqlite --kysely --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--sqlite--eslint--biome--oxlint
            flags: --solid --elysia --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--trpc--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --hono --trpc --sqlite --drizzle --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--trpc--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --hono --trpc --sqlite --kysely --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--trpc--sqlite--eslint--biome--oxlint
            flags: --solid --hono --trpc --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--telefunc--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --hono --telefunc --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--telefunc--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --hono --telefunc --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--telefunc--sqlite--eslint--biome--oxlint
            flags: --solid --hono --telefunc --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--ts-rest--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --hono --ts-rest --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--ts-rest--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --hono --ts-rest --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--ts-rest--sqlite--eslint--biome--oxlint
            flags: --solid --hono --ts-rest --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --hono --sqlite --drizzle --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --hono --sqlite --kysely --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--sqlite--eslint--biome--oxlint
            flags: --solid --hono --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--trpc--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --fastify --trpc --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--trpc--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --fastify --trpc --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--trpc--sqlite--eslint--biome--oxlint
            flags: --solid --fastify --trpc --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--telefunc--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --fastify --telefunc --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--telefunc--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --fastify --telefunc --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--telefunc--sqlite--eslint--biome--oxlint
            flags: --solid --fastify --telefunc --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--ts-rest--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --fastify --ts-rest --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--ts-rest--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --fastify --ts-rest --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--ts-rest--sqlite--eslint--biome--oxlint
            flags: --solid --fastify --ts-rest --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --fastify --sqlite --drizzle --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --fastify --sqlite --kysely --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--sqlite--eslint--biome--oxlint
            flags: --solid --fastify --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--trpc--eslint--biome--oxlint
            flags: --solid --express --trpc --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--telefunc--eslint--biome--oxlint
            flags: --solid --express --telefunc --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--ts-rest--eslint--biome--oxlint
            flags: --solid --express --ts-rest --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--eslint--biome--oxlint
            flags: --solid --express --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--trpc--eslint--biome--oxlint
            flags: --solid --hono --trpc --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--telefunc--eslint--biome--oxlint
            flags: --solid --hono --telefunc --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--ts-rest--eslint--biome--oxlint
            flags: --solid --hono --ts-rest --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--eslint--biome--oxlint
            flags: --solid --hono --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--trpc--eslint--biome--oxlint
            flags: --solid --fastify --trpc --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--telefunc--eslint--biome--oxlint
            flags: --solid --fastify --telefunc --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--ts-rest--eslint--biome--oxlint
            flags: --solid --fastify --ts-rest --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--fastify--eslint--biome--oxlint
            flags: --solid --fastify --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--trpc--eslint--biome--oxlint
            flags: --solid --elysia --trpc --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--telefunc--eslint--biome--oxlint
            flags: --solid --elysia --telefunc --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--ts-rest--eslint--biome--oxlint
            flags: --solid --elysia --ts-rest --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--elysia--eslint--biome--oxlint
            flags: --solid --elysia --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: react--hono--trpc--eslint--biome--oxlint
            flags: --react --hono --trpc --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: react--hono--telefunc--eslint--biome--oxlint
            flags: --react --hono --telefunc --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: react--hono--ts-rest--eslint--biome--oxlint
            flags: --react --hono --ts-rest --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: react--hono--eslint--biome--oxlint
            flags: --react --hono --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: vue--hono--trpc--eslint--biome--oxlint
            flags: --vue --hono --trpc --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: vue--hono--telefunc--eslint--biome--oxlint
            flags: --vue --hono --telefunc --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: vue--hono--ts-rest--eslint--biome--oxlint
            flags: --vue --hono --ts-rest --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: vue--hono--eslint--biome--oxlint
            flags: --vue --hono --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--telefunc--postgres--drizzle--eslint--biome--oxlint
            flags: --solid --express --telefunc --postgres --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--telefunc--postgres--kysely--eslint--biome--oxlint
            flags: --solid --express --telefunc --postgres --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--telefunc--postgres--eslint--biome--oxlint
            flags: --solid --express --telefunc --postgres --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--postgres--drizzle--eslint--biome--oxlint
            flags: --solid --express --postgres --drizzle --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--postgres--kysely--eslint--biome--oxlint
            flags: --solid --express --postgres --kysely --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--express--postgres--eslint--biome--oxlint
            flags: --solid --express --postgres --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--telefunc--postgres--drizzle--eslint--biome--oxlint
            flags: --solid --hono --telefunc --postgres --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--telefunc--postgres--kysely--eslint--biome--oxlint
            flags: --solid --hono --telefunc --postgres --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--telefunc--postgres--eslint--biome--oxlint
            flags: --solid --hono --telefunc --postgres --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--postgres--drizzle--eslint--biome--oxlint
            flags: --solid --hono --postgres --drizzle --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--postgres--kysely--eslint--biome--oxlint
            flags: --solid --hono --postgres --kysely --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--postgres--eslint--biome--oxlint
            flags: --solid --hono --postgres --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--cloudflare--trpc--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --hono --cloudflare --trpc --sqlite --drizzle --eslint
              --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--cloudflare--trpc--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --hono --cloudflare --trpc --sqlite --kysely --eslint
              --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--cloudflare--trpc--sqlite--eslint--biome--oxlint
            flags: --solid --hono --cloudflare --trpc --sqlite --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--cloudflare--telefunc--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --hono --cloudflare --telefunc --sqlite --drizzle --eslint
              --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--cloudflare--telefunc--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --hono --cloudflare --telefunc --sqlite --kysely --eslint
              --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--cloudflare--telefunc--sqlite--eslint--biome--oxlint
            flags: --solid --hono --cloudflare --telefunc --sqlite --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--cloudflare--ts-rest--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --hono --cloudflare --ts-rest --sqlite --drizzle --eslint
              --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--cloudflare--ts-rest--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --hono --cloudflare --ts-rest --sqlite --kysely --eslint
              --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--cloudflare--ts-rest--sqlite--eslint--biome--oxlint
            flags: --solid --hono --cloudflare --ts-rest --sqlite --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--cloudflare--sqlite--drizzle--eslint--biome--oxlint
            flags: --solid --hono --cloudflare --sqlite --drizzle --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--cloudflare--sqlite--kysely--eslint--biome--oxlint
            flags: --solid --hono --cloudflare --sqlite --kysely --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: solid--hono--cloudflare--sqlite--eslint--biome--oxlint
            flags: --solid --hono --cloudflare --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: react--hono--dokploy--telefunc--sqlite--drizzle--eslint--biome--oxlint
            flags: --react --hono --dokploy --telefunc --sqlite --drizzle --eslint
              --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: react--hono--dokploy--telefunc--sqlite--eslint--biome--oxlint
            flags: --react --hono --dokploy --telefunc --sqlite --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: react--hono--dokploy--telefunc--postgres--drizzle--eslint--biome--oxlint
            flags: --react --hono --dokploy --telefunc --postgres --drizzle --eslint
              --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: react--hono--dokploy--telefunc--postgres--eslint--biome--oxlint
            flags: --react --hono --dokploy --telefunc --postgres --eslint --biome
              --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: react--elysia--dokploy--telefunc--sqlite--drizzle--eslint--biome--oxlint
            flags: --react --elysia --dokploy --telefunc --sqlite --drizzle --eslint
              --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: react--elysia--dokploy--telefunc--postgres--drizzle--eslint--biome--oxlint
            flags: --react --elysia --dokploy --telefunc --postgres --drizzle
              --eslint --biome --oxlint
            test-files: FRAMEWORK+SERVER+DATA.spec.ts
          - destination: aws--react--hono--eslint--biome--oxlint
            flags: --aws --react --hono --eslint --biome --oxlint
            test-files: FRAMEWORK+aws.spec.ts
          - destination: react--cloudflare--hono--eslint--biome--oxlint
            flags: --react --cloudflare --hono --eslint --biome --oxlint
            test-files: FRAMEWORK+cloudflare.spec.ts
          - destination: react--cloudflare--eslint--biome--oxlint
            flags: --react --cloudflare --eslint --biome --oxlint
            test-files: FRAMEWORK+cloudflare.spec.ts
          - destination: react--edgeone--eslint--biome--oxlint
            flags: --react --edgeone --eslint --biome --oxlint
            test-files: FRAMEWORK+edgeone.spec.ts
          - destination: vue--netlify--eslint--biome--oxlint
            flags: --vue --netlify --eslint --biome --oxlint
            test-files: FRAMEWORK+netlify.spec.ts
          - destination: solid--prettier--eslint--biome--oxlint
            flags: --solid --prettier --eslint --biome --oxlint
            test-files: FRAMEWORK+prettier.spec.ts
          - destination: react--hono--prisma--sqlite--eslint--biome--oxlint
            flags: --react --hono --prisma --sqlite --eslint --biome --oxlint
            test-files: FRAMEWORK+prisma.spec.ts
          - destination: vue--hono--prisma--postgres--eslint--biome--oxlint
            flags: --vue --hono --prisma --postgres --eslint --biome --oxlint
            test-files: FRAMEWORK+prisma.spec.ts
          - destination: react--sentry--eslint--biome--oxlint
            flags: --react --sentry --eslint --biome --oxlint
            test-files: FRAMEWORK+sentry.spec.ts
          - destination: vue--sentry--eslint--biome--oxlint
            flags: --vue --sentry --eslint --biome --oxlint
            test-files: FRAMEWORK+sentry.spec.ts
          - destination: solid--sentry--eslint--biome--oxlint
            flags: --solid --sentry --eslint --biome --oxlint
            test-files: FRAMEWORK+sentry.spec.ts
          - destination: react--claude
            flags: --react --claude
            test-files: FRAMEWORK+skills.spec.ts
          - destination: vue--claude
            flags: --vue --claude
            test-files: FRAMEWORK+skills.spec.ts
          - destination: solid--claude
            flags: --solid --claude
            test-files: FRAMEWORK+skills.spec.ts
          - destination: react--hono--trpc--sqlite--drizzle--codex--gemini
            flags: --react --hono --trpc --sqlite --drizzle --codex --gemini
            test-files: FRAMEWORK+skills.spec.ts
          - destination: solid--storybook--eslint
            flags: --solid --storybook --eslint
            test-files: FRAMEWORK+storybook.spec.ts
          - destination: react--vercel--hono--eslint--biome--oxlint
            flags: --react --vercel --hono --eslint --biome --oxlint
            test-files: FRAMEWORK+vercel.spec.ts
          - destination: react--vercel--express--eslint--biome--oxlint
            flags: --react --vercel --express --eslint --biome --oxlint
            test-files: FRAMEWORK+vercel.spec.ts
          - destination: react--vercel--fastify--eslint--biome--oxlint
            flags: --react --vercel --fastify --eslint --biome --oxlint
            test-files: FRAMEWORK+vercel.spec.ts
          - destination: react--vercel--elysia--eslint--biome--oxlint
            flags: --react --vercel --elysia --eslint --biome --oxlint
            test-files: FRAMEWORK+vercel.spec.ts
          - destination: react--vercel--eslint--biome--oxlint
            flags: --react --vercel --eslint --biome --oxlint
            test-files: FRAMEWORK+vercel.spec.ts
          - destination: react--compiled-css--eslint--biome
            flags: --react --compiled-css --eslint --biome
            test-files: react+UI.spec.ts
          - destination: react--mantine--eslint--biome
            flags: --react --mantine --eslint --biome
            test-files: react+UI.spec.ts
          - destination: react--ts-rest--hono--eslint
            flags: --react --ts-rest --hono --eslint
            test-files: remove-linter-comments.spec.ts
          - destination: react--ts-rest--hono--biome
            flags: --react --ts-rest --hono --biome
            test-files: remove-linter-comments.spec.ts
          - destination: react--ts-rest--hono--oxlint
            flags: --react --ts-rest --hono --oxlint
            test-files: remove-linter-comments.spec.ts
      fail-fast: false

    name: Run ${{ matrix.flags }}

    uses: ./.github/workflows/reusable.run-tests.yml
    secrets: inherit
    with:
      os: ubuntu-latest
      destination: ${{ matrix.destination }}
      flags: ${{ matrix.flags }}
      test-files: ${{ matrix.test-files }}
