# Step 1
name: Tests

on:
  pull_request:
    paths-ignore:
      - 'website/**'
  push:
    # Ensures cache is computed on main branch so that it can be reused on all PRs
    branches: [ "main" ]
    paths-ignore:
      - 'website/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  monorepo:
    strategy:
      matrix:
#        FIXME Windows tests are not terminating, and GH CI terminates them after many hours
        os: [ ubuntu-latest, macos-latest ]
#        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node: [ 20 ]
      fail-fast: false

    uses: ./.github/workflows/tests-entry-os.reusable.yml
    secrets: inherit
    with:
      os: ${{ matrix.os }}
      node: ${{ matrix.node }}
      fast: ${{ matrix.os != 'ubuntu-latest' }}
